# Dependencies
markdown:         kramdown
highlighter:      rouge
remote_theme:     fongandrew/hydeout

# Setup
title:            Manish Sihag
tagline:          'Portfolio'
description:      'IIT Bombay Graduate | Data Scientist | Web Developer | AI in Drug Discovery'
url:              https://sihagmnis36.github.io
# baseurl:          '/'
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           'Manish Sihag'
  url:            https://github.com/sihagmnis36

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

include: ['_projects']
# Sidebar link settings
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
collections:
  projects:
    output: true

disqus:
  shortname: sihagmnis36-github-io

google_analytics: UA-177002244-1